import ProtectedRoute from "@/ProtectedRoute/ProtectedRoute";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <section className={inter.className}>
      <ProtectedRoute>
        <Toaster />
        {children}
      </ProtectedRoute>
    </section>
  );
}
